### ISSUE TITLE
Give access to the Vue object (e.g. vue-resource in models)

### ISSUE THREAD

**Issue by marvinroger** [egoist/eva.js#9]
I register `VueResource` with `app.use()` and it works fine from within my components, as I can access `this.$http`. However, if we want to use `VueResource` outside of the components (inside of models for example), we have to access it directly on the vue instance, through `vue.http`. But eva does not provide access to the underlying vue instance. Or maybe I am missing something?

**Comment by egoist** [comment]
update `eva.js`, now you can `import {Vue} from 'eva.js'`

**Comment by marvinroger** [comment]
Awesome, `Eva.Vue.use` sounds cleaner than `app.use()` IMO (explicit over implicit).
Thanks!

**Comment by marvinroger** [comment]
Great project, by the way. So simple, but so useful.

**Comment by egoist** [comment]
Glad to hear that 😃

![news-atl-down-MTclfCr4tVgis](https://camo.githubusercontent.com/94be8a09380e9eb9f3c51d3f1c61b9a4a8af2b4c/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4d54636c6643723474566769732f67697068792e676966)
